### ISSUE TITLE
Google Search Sidebar Needs Updating

### ISSUE THREAD

**Issue by TV107** [jmlntw/google-search-sidebar#14]
Please update Google Search Sidebar ... with Google's new material icons debuting there is a picture next to all the categories and the maps/videos/shopping/news/images/etc are not centered ... please fix

if you fix it within 2 weeks, I'll paypal you $5.00 if you give me an e-mail address to send it

also, if you could create a script that gets rid of the icons and goes back to text-only categories would be great

**Comment by TV107** [comment]
here is a screenshot of how google is processing your script now: https://hmp.me/cmcl

**Comment by TV107** [comment]
sorry i don't want it centered....i want it on the left, as it was before ... now it's on the right

**Comment by TV107** [comment]
https://9to5google.com/2019/06/13/google-search-material-theme-icons/?fbclid=IwAR3zWnhavNG886cn2BjcQ8oaawu4f2tJ3l0ZxgqZ8_V_YBtocvtBqdGXFD4

**Comment by mnghsn** [comment]
Thanks for your feedback. I'll look into it in the next few days and see what I can do.

**Comment by mnghsn** [comment]
Fixed in **v0.3.3**.

**Comment by TV107** [comment]
thanks .... you moved it all the way over to the left, google starts it indented a bit (so you might want to see what other people think for your next update whenever in the future) ... i guess ideal would be half-way in-between what you did and what google does as your #1 choice based on query whether it be news or videos or whatever should be below the left of the search query bar ... but anyway much better than the far right!!
