### ISSUE TITLE
support FireMonkey

### ISSUE THREAD

**Issue by nobura** [jmlntw/google-search-sidebar#21]
https://addons.mozilla.org/en-US/firefox/addon/firemonkey/

The extension supports GreaseMonkey GM3 and GM4 functions and functions provided by the Firefox API. Some scripts may not work properly when you create or import them; the Firefox API does not allow wildcard top level domains (TLD) which means that something like http*://www.google.*/* is not supported. It may be necessary to adjust scripts accordingly so that they may be imported without issues.

**Comment by mnghsn** [comment]
FireMonkey v1.25 supports TLD wildcard for `@include` and this script is working on FIreMonkey now. 👍
