### ISSUE TITLE
Cannot work after the upgrade.

### ISSUE THREAD

**Issue by weal1312** [jmlntw/google-search-sidebar#24]
在Google近期更新版面以後，必須先點選Tool才能正常顯示側邊欄
以目前預設會用display:none隱藏掉#hdtb-tls的寫法不能正常運作

**Comment by mnghsn** [comment]
剛剛測試過是沒問題的，可以的話請請提供瀏覽器版本、出問題的網址等詳細資訊。
可能是和 #22 遇到一樣問題（A/B 測試）。

**Comment by weal1312** [comment]
系統是Win 使用新Microsoft Edge  80.0.361.54，配合xStyle 3.1.2
重新測試了一下，不登入Google帳號時運作正常，但只要一登入就會失效
問題跟#22是一樣的

**Comment by mnghsn** [comment]
併至 #22 討論。
