### ISSUE TITLE
not working in google image

### ISSUE THREAD

**Issue by nobura** [jmlntw/google-search-sidebar#25]
script is not working in google image anymore

**Comment by mnghsn** [comment]
Google now uses JavaScript to dynamically generate the search menu on Google Image Search, so there is nothing CSS can do about it. I will try to support Google Image Search in UserScript version.

UserCSS version may only have limited functions in the future.

**Comment by fharper** [comment]
Supporting image would be awesome! Thanks for this script, loving it.

**Comment by mnghsn** [comment]
It seems Google has reverted to a static menu in image search, which has restored the script's functionality. I consider this issue resolved.
