### ISSUE TITLE
Move User style to GreasyFork

### ISSUE THREAD

**Issue by mnghsn** [jmlntw/google-search-sidebar#26]
Since Userstyles.org lacks maintenance and does not support automatic updates, I'm considering moving User CSS to GreasyFork in next major version.

> Greasy Fork supports user styles now, in the Stylus user style format.
> Greasy Fork is actively developed and moderated. You can set up the styles you wrote to sync from your GitHub or any URL you like, and Greasy Fork will pull in updates.
>
> The list of styles posted on Greasy Fork is admittedly very limited right now, but we're committed to supporting user style authors and hopefully we'll get it expanded.
>
> https://forum.userstyles.org/discussion/83785/if-youd-like-a-site-thats-not-falling-apart-try-greasyfork-org

**Comment by mikhoul** [comment]
It's a good idea but keep it here also since it's more appropriate to debug/fork the project.

Regards :octocat:
