### ISSUE TITLE
Not Working and New Problem

### ISSUE THREAD

**Issue by TV107** [jmlntw/google-search-sidebar#29]
Not only does it not work anymore, but there is another problem
When you hover over news, books, images, maps, etc, it says .,..Shift + N, Shift + B,
see image below

Please fix and remove this new nuisance and if you can do both I'll donate $10USD to your paypal.

![news](https://user-images.githubusercontent.com/51813249/94869060-75f75d00-0412-11eb-82d5-e0c175da5c46.png)

**Comment by mnghsn** [comment]
Duplicated with #28.

I don't see any tooltips in both Firefox and Chrome. Maybe that is from other browser extension or accessibility tools.

**Comment by TV107** [comment]
No, it has nothing to do with the browser .... however it only happens when I am signed into my google account ... doesn't occur when signed out ... are you testing this when you are signed in?

**Comment by mnghsn** [comment]
Yes, I also tested this when I'm signed in and I still don't see any tooltips.

The main purpose of this script is to show the sidebar menus and this tooltip issue is a bit off-topic. I'll mark it as wontfix.
