### ISSUE TITLE
menu auto show up after search

### ISSUE THREAD

**Issue by yyysuo** [jmlntw/google-search-sidebar#33]
chrome version:86.0.4240.193
windows version:19042.630
stylus version:1.5.13

when search is done,all menus auto shows up.

![20201111085745](https://user-images.githubusercontent.com/10081071/98752151-8977e980-23fc-11eb-9ad9-1c49ba071457.jpg)

**Comment by samxoxo101** [comment]
![火狐截图_2020-11-11T06-05-16 883Z](https://user-images.githubusercontent.com/73594319/98774969-0fa92580-2427-11eb-8a52-17e46915872c.png)

Firefox ESR 78.2.0 也中獎了😓😥

**Comment by op69qs** [comment]
感谢
