### ISSUE TITLE
Problems with Script in "All" Results of Google

### ISSUE THREAD

**Issue by TV107** [jmlntw/google-search-sidebar#44]
This script has been buggy, esp. lately in the in the main or "All" search page of Google .... not in the "Videos, "News"   It works if you are way zoomed out but if if you zoomed in to a reasonable decent font for your eyes,, there is  OVERLAP with the script (recent, past hour, past 24 hours, etc.) and google results -- again only in the "All" not in the "Videos, "News," ---- but since "All" is the main window,  it makes the script kinda ususable in my main browser.  It seems kinda better on my laptop than on my desktop, but I can't figure out any fix, whether cookies or resetting...it's definitely sometimes that needs adjusting in the actual code.
Is there any way of the scripti noticing/checking-in on the zoomed-in quality of the font on the "All" page and aligning the text better (shifting the google results to the right) as it seems to do on all the other sections of Google where this user script is used?

**Comment by mnghsn** [comment]
Thanks for your feedback. I don't have too much time to work on this project right now but I'm planning to get back to it in the next few weeks.

**Comment by mnghsn** [comment]
After my own testing, I think that the issue you mentioned is fixed in the latest version (v0.3.10). Please give it a try and feel free to reopen this issue if you are still running into issues.

**Comment by TV107** [comment]
thank you VERY much ... much much better ... still not 100% perfect though ... for example, if you type "bieber" (or any famous person) and you are zoomed in, you get the left part of their name cut off  ... otherwise, it seems great (in very preliminary testing)
![bieber](https://user-images.githubusercontent.com/51813249/169638768-dd9f05eb-4534-44ad-86c7-f42c5331d80d.png)
