### ISSUE TITLE
Userstyles.org 出現空樣式段

### ISSUE THREAD

**Issue by weal1312** [jmlntw/google-search-sidebar#6]
使用Stylus，出現一段無效的樣式段，需手動刪除
![Imgur](https://i.imgur.com/tPjo2hO.png)
不算太大的問題，但希望能夠解決
個人猜測是前面那段/* ==UserStyle== ... */的註解造成的

另外，也希望能加進類似Google Search Tools Back那樣，直接顯示搜尋結果頁庫存檔和類似內容的功能

**Comment by mnghsn** [comment]
`/* ==UserStyle== */` 那一段當初是針對 xStyle 所寫的 metablock（參考 FirefoxBar/xStyle#25）。Stylus 也有相關的實作正在討論中（參考 openstyles/stylus#134）。

這個樣式原本只打算針對側欄處理，所以沒有處理頁庫存檔的下拉選單（所以才叫做「Google Search **Sidebar**」）。不過我收到不只一次希望顯示頁庫存檔的意見，所以或許會在下一個版本做出來。
